---
fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.13.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "7.4.0"
    powershell:
      repo: "puppetlabs/powershell"
      ref: "5.2.0"
